defaults: &defaults
  access_key_id: "AKIAJM766EMS3GJJ7I5Q"
  secret_access_key: "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"
  bucket: "p1012015"
development:
  <<: *defaults
 
test:
  <<: *defaults
  
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "p1012015"